services:
  neo4j-db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
       - NEO4J_AUTH=neo4j/password
       - NEO4J_PLUGINS=["apoc"]
    volumes:
       - $HOME/neo4j/data:/data
       - $HOME/neo4j/logs:/logs
       - $HOME/neo4j/plugins:/plugins
       - $HOME/neo4j/import:/import
       - $HOME/neo4j/backups:/backups
